---
- name: Include OS specific variables
  include_vars: "{{ ansible_os_family }}.yml"
  tags: ["distribution", "packages", "service", "monit"]

- include: install.yml
  tags: ["monit", "install"]

- include: configure.yml
  tags: ["monit", "configure"]

- include: monitor.yml
  tags: ["monit", "monitor"]

