---
- name: Create default system monitor
  template:
    src: system.j2
    dest: "{{ monit_config_dir }}/{{ ansible_hostname }}"
    owner: "{{ monit_user }}"
    group: "{{ monit_group }}"
    mode: 0644
  when: monit_monitoring_system
  notify: reload monit


- block:
  - name: Delete monitors
    file: path="{{ monit_config_dir }}/{{ item.name }}" state=absent
    with_items: "{{ monit_monitoring_list }}"
    when: item.delete is defined and item.delete
    notify: reload monit

  - name: Add monitors
    template:
      src: monitor.j2
      dest: "{{ monit_config_dir }}/{{ item.name }}"
      owner: "{{ monit_user }}"
      group: "{{ monit_group }}"
      mode: 0644
    with_items: "{{ monit_monitoring_list }}"
    when: not (item.delete is defined and item.delete)
    notify: reload monit

  when: monit_monitoring_list

